[tool.black]
line-length = 119

[tool.flake8]
extend-ignore = "E203"
max-line-length = 119

[tool.isort]
profile = "black"
line_length = 119

[tool.mypy]
ignore_missing_imports = true

[tool.pylint.format]
max-line-length = 119

[tool.pylint.message_control]
disable = [
    "C0114", # missing-module-docstring
    "C0115", # missing-class-docstring
    "C0116", # missing-function-docstring
    "R0801", # duplicate-code
    "R0903", # too-few-public-methods
]
