name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  DEFAULT_PYTHON: 3.9
  PIPENV_VENV_IN_PROJECT: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Python ${{env.DEFAULT_PYTHON}}
        id: python
        uses: actions/setup-python@main
        with:
          python-version: ${{env.DEFAULT_PYTHON}}
      - name: Setup pipenv
        run: pip install --user pipenv
      - name: Create virtual environment
        run: |
          pipenv --python ${{env.DEFAULT_PYTHON}}
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev
          pipenv run python -m pip install -U pip
          pipenv sync --dev
      - name: Run formatter and linter
        run: pipenv run fix
