env:
  browser: true
  es2021: true
extends:
  - "plugin:react/recommended"
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - import
  - jsx-a11y
  - react
  - react-hooks
overrides:
  - files: "./src/**/*.{js,jsx,ts,tsx}"
    rules:
      import/order:
        - error
        - groups:
            - builtin
            - external
            - parent
            - sibling
            - index
            - object
            - type
          pathGroups:
            - group: parent
              pattern: "@alias/**"
              position: before
          alphabetize:
            order: asc
          newlines-between: always
rules: {}
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
    typescript:
      alwaysTryTypes: true
